### ISSUE TITLE
Bug in example

### ISSUE THREAD

**Issue by jahands** [ajkachnic/replit-database-deno#1]
Get Started shows this:
```typescript
import { Client } from "https://deno.land/x/replit_database/mod.ts";
const client = new Client();
await Client.set("key", "value");
let key = await Client.get("key");
console.log(key);
```

When it should show this (notice capitalization of `client`):
```typescript
import { Client } from "https://deno.land/x/replit_database/mod.ts";
const client = new Client();
await client.set("key", "value");
let key = await client.get("key");
console.log(key);
```

**Comment by ajkachnic** [comment]
Ah thank you! I think this was a bug in the original repo and got brought in when I copied the docs. Regardless, I'll make a fix

**Comment by jahands** [comment]
Thanks! Yeah there's an [open PR](https://github.com/replit/database-node/pull/8) in the original repo as well.
